gameworldname:
defaulthealth:
Team:
  RED:
    end_stone:
      x:
      y:
      z:
    spawnpoint:
      x:
      y:
      z:
    protect:
      x1:
      y1:
      z1:
      x2:
      y2:
      z2:
  YELLOW:
    end_stone:
      x:
      y:
      z:
    spawnpoint:
      x:
      y:
      z:
    protect:
      x1:
      y1:
      z1:
      x2:
      y2:
      z2:
  GREEN:
    end_stone:
      x:
      y:
      z:
    spawnpoint:
      x:
      y:
      z:
    protect:
      x1:
      y1:
      z1:
      x2:
      y2:
      z2:
  BLUE:
    end_stone:
      x:
      y:
      z:
    spawnpoint:
      x:
      y:
      z:
    protect:
      x1:
      y1:
      z1:
      x2:
      y2:
      z2: